version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: studentdb.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: studentdb
      MYSQL_USER: student_user
      MYSQL_PASSWORD: student_pass
    ports:
      - "3306:3306"
    volumes:
      - student_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  student_mysql_data: